/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Matriz;

import javax.swing.JOptionPane;

/**
 *
 * @author duvan
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    int tamaño;
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Suma = new javax.swing.JButton();
        Resta = new javax.swing.JButton();
        Traza = new javax.swing.JButton();
        Determinante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora");

        Suma.setText("Suma");
        Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActionPerformed(evt);
            }
        });

        Resta.setText("Resta");
        Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaActionPerformed(evt);
            }
        });

        Traza.setText("Traza");
        Traza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrazaActionPerformed(evt);
            }
        });

        Determinante.setText("Determinante");
        Determinante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeterminanteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("+");

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("/");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("D");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Suma)
                    .addComponent(Traza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Determinante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Resta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Suma)
                    .addComponent(Resta))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Traza)
                    .addComponent(Determinante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaActionPerformed
        tamaño = Integer.parseInt(JOptionPane.showInputDialog("Tamaño de las matrices"));

        int mat1[][] = new int[tamaño][tamaño];
        int mat2[][] = new int[tamaño][tamaño];
        int mat3[][] = new int[tamaño][tamaño];

        if (tamaño > 1) {
            JOptionPane.showMessageDialog(null, "Llene las matrices");

            JOptionPane.showMessageDialog(null, "Matriz 1");
            for (int i = 0; i < mat1.length; i++) {
                for (int j = 0; j < mat1.length; j++) {

                    mat1[i][j] = Integer.parseInt(JOptionPane.showInputDialog("llenar posicion: fila: " + (i + 1) + "Columna: " + (j + 1)));
                }
            }

            JOptionPane.showMessageDialog(null, "Matriz 2");
            for (int i = 0; i < mat2.length; i++) {
                for (int j = 0; j < mat2.length; j++) {

                    mat2[i][j] = Integer.parseInt(JOptionPane.showInputDialog("llenar posicion: fila: " + (i + 1) + "Columna: " + (j + 1)));
                }
            }

            JOptionPane.showMessageDialog(null, "sumando matrices....");
            for (int i = 0; i < mat3.length; i++) {
                for (int j = 0; j < mat3.length; j++) {
                    mat3[i][j] = mat1[i][j] + mat2[i][j];
                }
            }

            JOptionPane.showMessageDialog(null, "matriz resultante:");
            String s = "";

            for (int i = 0; i < mat3.length; i++) {
                for (int j = 0; j < mat3.length; j++) {
                    s += mat3[i][j];
                    s += "";

                }
                s += "\n";
            }
            JOptionPane.showMessageDialog(null, s);
        }
    
                                               

    }//GEN-LAST:event_SumaActionPerformed

    private void RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaActionPerformed
        tamaño = Integer.parseInt(JOptionPane.showInputDialog("Tamaño de las matrices"));

        int mat1[][] = new int[tamaño][tamaño];
        int mat2[][] = new int[tamaño][tamaño];
        int mat3[][] = new int[tamaño][tamaño];

        if (tamaño > 1) {

            JOptionPane.showMessageDialog(null, "Llene las matrices");

            JOptionPane.showMessageDialog(null, "Matriz 1");
            for (int i = 0; i < mat1.length; i++) {
                for (int j = 0; j < mat1.length; j++) {

                    mat1[i][j] = Integer.parseInt(JOptionPane.showInputDialog("llenar posicion: fila: " + (i + 1) + "Columna: " + (j + 1)));
                }
            }

            JOptionPane.showMessageDialog(null, "Matriz 2");
            for (int i = 0; i < mat2.length; i++) {
                for (int j = 0; j < mat2.length; j++) {

                    mat2[i][j] = Integer.parseInt(JOptionPane.showInputDialog("llenar posicion: fila: " + (i + 1) + "Columna: " + (j + 1)));
                }
            }

            JOptionPane.showMessageDialog(null, "restando matrices....");
            for (int i = 0; i < mat3.length; i++) {
                for (int j = 0; j < mat3.length; j++) {
                    mat3[i][j] = mat1[i][j] - mat2[i][j];
                }
            }

            JOptionPane.showMessageDialog(null, "matriz resultante:");
            String s = "";

            for (int i = 0; i < mat3.length; i++) {
                for (int j = 0; j < mat3.length; j++) {
                    s += mat3[i][j];
                    s += "";

                }
                s += "\n";
            }
            JOptionPane.showMessageDialog(null, s);
        }
    }//GEN-LAST:event_RestaActionPerformed

    private void TrazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrazaActionPerformed
        tamaño = Integer.parseInt(JOptionPane.showInputDialog("Tamaño de las matriz"));

        int mat1[][] = new int[tamaño][tamaño];
        int mat2[][] = new int[tamaño][tamaño];

        if (tamaño > 1) {
            JOptionPane.showMessageDialog(null, "Llene la matriz");
            for (int i = 0; i < mat1.length; i++) {
                for (int j = 0; j < mat1.length; j++) {

                    mat1[i][j] = Integer.parseInt(JOptionPane.showInputDialog("llenar posicion: fila: " + (i + 1) + "Columna: " + (j + 1)));
                }
            }

            JOptionPane.showMessageDialog(null, "trazando matriz....");
            for (int i = 0; i < mat1.length; i++) {
                for (int j = 0; j < mat1.length; j++) {
                    if (i == j) {
                        mat2[i][j] = mat1[i][j];
                    }
                }
            }

            JOptionPane.showMessageDialog(null, "matriz resultante:");
            String s = "";

            for (int i = 0; i < mat2.length; i++) {
                for (int j = 0; j < mat2.length; j++) {
                    if (i == j) {
                        s += mat2[i][j];
                        s += "";
                    }
                }
                s += "+";
            }
            JOptionPane.showMessageDialog(null, "T = La suma de " + s);
        }
    }//GEN-LAST:event_TrazaActionPerformed

    private void DeterminanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeterminanteActionPerformed
        tamaño = Integer.parseInt(JOptionPane.showInputDialog("Tamaño de las matriz"));

        int mat1[][] = new int[tamaño][tamaño];
        JOptionPane.showMessageDialog(null,"Empieze a llenar la matriz");
        for (int i = 0; i < tamaño; i++) {
            for (int j = 0; j < tamaño; j++) {
                mat1[i][j]=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el valor de la fila: "+(i+1)+" y la columna: "+(j+1)));      
                
            } 
        }
        JOptionPane.showMessageDialog(null,"la determinante de la matriz es:"+Det.determinanteMatriz(mat1, tamaño));                                        

    }//GEN-LAST:event_DeterminanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Determinante;
    private javax.swing.JButton Resta;
    private javax.swing.JButton Suma;
    private javax.swing.JButton Traza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
